# Generated by Django 5.2.7 on 2025-11-11 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_communitypost_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic - $50'), ('standard', 'Standard - $100'), ('premium', 'Premium - $500'), ('bots', 'Bots Account - Setup Fee $100')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('access_level', models.CharField(choices=[('telegram', 'Telegram Only'), ('signals', 'Signals & Telegram'), ('bots', 'Bots & Signals & Telegram'), ('all', 'Full Access (Signals, Bots, Classes)')], default='telegram', max_length=20)),
                ('features', models.TextField(help_text='List of features included in this subscription')),
                ('can_access_signals', models.BooleanField(default=False)),
                ('can_access_bots', models.BooleanField(default=False)),
                ('can_access_classes', models.BooleanField(default=False)),
                ('can_access_community', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tier',
        ),
        migrations.AddField(
            model_name='purchase',
            name='bots_setup_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.subscription'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bots_setup_fee_paid', models.BooleanField(default=False)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_premium_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
